name: Feature Request
description: Create a feature request
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature request
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why should this be added?
      description:
        What is the reason for this feature request? What problem does it solve? What would it
        improve?
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        Add any other context about the feature request here.
        Screenshots, logs, or other files are also accepted.
  - type: checkboxes
    id: terms
    attributes:
      label: Please confirm the following
      options:
        - label:
            This is a feature request for Replugged itself, not a feature request for a plugin or
            theme
          required: true
        - label:
            "[I searched the issues](https://github.com/replugged-org/replugged/issues) to make sure
            this feature has not been requested before."
          required: true
